- hosts: localhost
  vars:
    source_personal_ssh_key: "./.ssh/id_ed25519"
    dest_personal_ssh_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    source_work_ssh_key: "./.ssh/id_ed25519-melt"
    dest_work_ssh_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519-melt"
    zsh_custom: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom"
    third_parties: "{{ lookup('env', 'HOME') }}/repos/third-parties"
    deb_architecture: { "aarch64": "arm64", "x86_64": "amd64" }
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/ssh-work.yml
    - include: tasks/gpg.yml
    - include: tasks/core-packages.yml
    - include: tasks/speedtest.yml
    - include: tasks/git-delta.yml
    - include: tasks/zsh.yml
    - include: tasks/from-source-packages.yml
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
    - include: tasks/nvim.yml
    - include: tasks/docker.yml
    - include: tasks/lazygit.yml
    - include: tasks/kitty.yml
    - include: tasks/pyenv.yml
    - include: tasks/flatpak-packages.yml
    - include: tasks/fonts.yml
    - include: tasks/dotfiles.yml
