- hosts: localhost
  vars:
    source_personal_ssh_key: "./.ssh/id_ed25519"
    dest_personal_ssh_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    source_work_ssh_key: "./.ssh/id_ed25519-melt"
    dest_work_ssh_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519-melt"
    zsh_custom: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom"
    third_parties: "{{ lookup('env', 'HOME') }}/repos/third-parties"
    deb_architecture: { "aarch64": "arm64", "x86_64": "amd64" }
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
  tasks:
    - import_tasks: common/ssh.yml
    - import_tasks: pop-os/ssh-work.yml
    - import_tasks: pop-os/gpg.yml
    - import_tasks: pop-os/core-packages.yml
    - import_tasks: common/oh-my-zsh.yml
    - import_tasks: pop-os/speedtest.yml
    - import_tasks: pop-os/git-delta.yml
    - import_tasks: pop-os/reactotron.yml
    - import_tasks: pop-os/gh.yml
    - import_tasks: pop-os/zsh.yml
    - import_tasks: pop-os/from-source-packages.yml
    - import_tasks: common/nnn.yml
    - import_tasks: common/node.yml
    - import_tasks: pop-os/npm-packages.yml
    - import_tasks: common/nvim.yml
    - import_tasks: pop-os/docker.yml
    - import_tasks: pop-os/libinput-gestures.yml
    - import_tasks: common/lazygit.yml
    - import_tasks: pop-os/kitty.yml
    - import_tasks: pop-os/pyenv.yml
    - import_tasks: pop-os/nordvpn.yml
    - import_tasks: pop-os/flatpak-packages.yml
    - import_tasks: common/fonts.yml
    - import_tasks: pop-os/dotfiles.yml
    - import_tasks: mac-os/core-packages.yml
