- name: Update apt cache
  become: true
  apt:
    update_cache: yes
  tags:
    - core-packages

- name: "Install system packages"
  become: true
  apt:
    name:
      [
        "unzip",
        "copyq",
        "libgirepository1.0-dev",
        "apt-show-versions",
        "bpytop",
        "cpu-checker",
        "picom",
        "pavucontrol",
        "git-extras",
        "xclip",
        "dunst",
        "gawk",
        "libnotify-bin",
        "scrcpy",
        "flameshot",
        "python3-pygments",
        "tree",
        "ripgrep",
        "tmux",
        "fortune-mod",
        "bat",
        "chafa",
        "exiftool",
        "direnv",
        "stow",
        "xbindkeys",
        "autoconf",
        "automake",
        "libtool",
        "libmagickwand-dev",
        "gtk-doc-tools",
      ]
    state: present
  tags:
    - core-packages

- name: "Install nnn dependecies"
  become: true
  apt:
    name: ["pkg-config", "libncursesw5-dev", "libreadline-dev"]
  tags:
    - core-packages

- name: "Install java runtime"
  become: true
  apt:
    name: "openjdk-11-jdk"
  tags:
    - core-packages

- name: "instal 'useful' packages"
  become: true
  apt:
    name: ["sl", "neofetch"]

- name: "Install pyenv dependecies"
  become: true
  apt:
    name:
      [
        build-essential,
        libssl-dev,
        zlib1g-dev,
        libbz2-dev,
        libreadline-dev,
        libsqlite3-dev,
        curl,
        libncursesw5-dev,
        xz-utils,
        tk-dev,
        libxml2-dev,
        libxmlsec1-dev,
        libffi-dev,
        liblzma-dev,
      ]
    state: present
  tags:
    - core-packages
