- name: "Update apt cache"
  apt:
    update_cache: yes
  tags:
    - docker

- name: "Install required packages"
  apt:
    name: ["ca-certificates", "curl", "gnupg"]
    state: present
  tags:
    - docker

- name: "Create directory for keyrings"
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  tags:
    - docker

- name: "Import Docker GPG key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.gpg
  tags:
    - docker

- name: "Set permissions for Docker GPG key"
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: "0644"
  tags:
    - docker

- name: Add Docker repository entry to sources.list.d
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    create: yes
    state: present
  become: yes
  tags:
    - docker

- name: Update apt cache
  apt:
    force_apt_get: true
    update_cache: true
  tags:
    - docker

- name: Install Docker packages and plugins
  apt:
    force_apt_get: true
    name: ["docker-ce", "docker-ce-cli", "containerd.io", "docker-buildx-plugin", "docker-compose-plugin"]
    state: present
  tags:
    - docker

