- name: "Install Flatpak package"
  become: true
  apt:
    name: flatpak
    state: present
  tags:
    - flatpak

- name: "Add Flathub remote repository"
  shell: flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  tags:
    - flatpak

- name: "Install spotify client"
  flatpak:
    name: https://dl.flathub.org/repo/appstream/com.spotify.Client.flatpakref
    method: user
    state: present
  tags:
    - flatpak
    - spotify

- name: "Install dbeaver client"
  flatpak:
    name: https://dl.flathub.org/repo/appstream/io.dbeaver.DBeaverCommunity.flatpakref
    method: user
    state: present
  tags:
    - flatpak
    - dbeaver

- name: "Install tor web-browser client"
  flatpak:
    name: https://dl.flathub.org/repo/appstream/com.github.micahflee.torbrowser-launcher.flatpakref
    method: user
    state: present
  tags:
    - flatpak
    - tor

- name: "Install obs studio"
  flatpak:
    name: https://dl.flathub.org/repo/appstream/com.obsproject.Studio.flatpakref
    method: user
    state: present
  tags:
    - flatpak
    - obs

- name: "Install discord client"
  flatpak:
    name: https://dl.flathub.org/repo/appstream/com.discordapp.Discord.flatpakref
    method: user
    state: present
  tags:
    - flatpak
    - discord

- name: "Install slack client"
  flatpak:
    name: https://dl.flathub.org/repo/appstream/com.slack.Slack.flatpakref
    method: user
    state: present
  tags:
    - flatpak
    - slack

- name: "Install Android Studio IDE"
  flatpak:
    name: https://dl.flathub.org/repo/appstream/com.google.AndroidStudio.flatpakref
    method: user
    state: present
  tags:
    - flatpak
    - android-studio

- name: "Install Google Chrome Web Browser"
  flatpak:
    name: https://dl.flathub.org/repo/appstream/com.google.Chrome.flatpakref
    method: user
    state: present
  tags:
    - flatpak
    - chrome

- name: "Install Brave Web Browser"
  flatpak:
    name: https://dl.flathub.org/repo/appstream/com.brave.Browser.flatpakref
    method: user
    state: present
  tags:
    - flatpak
    - brave
