- name: Copy .fonts contents
  copy:
    src: fonts/.fonts
    dest: "{{ lookup('env', 'HOME') }}"
    mode: 0644
  tags:
    - fonts

- name: erase font cache
  shell: fc-cache -fv
  args:
    executable: /bin/sh
  tags:
    - fonts
