- name: "Download Kitty installer script"
  get_url:
    url: https://sw.kovidgoyal.net/kitty/installer.sh
    dest: /tmp/installer.sh
    mode: "0755"
  tags:
    - kitty

- name: "Run Kitty installer script"
  shell: sh /tmp/installer.sh dest="{{ lookup('env', 'HOME') }}/.local/stow"
  args:
    executable: /bin/sh
  tags:
    - kitty

- name: "Stow Kitty application"
  command: stow -v kitty.app
  args:
    chdir: "{{ lookup('env', 'HOME') }}/.local/stow"
  tags:
    - kitty
