- name: Get latest reactotron release version
  get_url:
    url: "https://api.github.com/repos/infinitered/reactotron/releases/latest"
    dest: "/tmp/reactotron_release.json"
  tags:
    - reactotron

- name: Extract reactotron version from release JSON
  set_fact:
    reactotron_version: "{{ lookup('file', '/tmp/reactotron_release.json') | from_json | json_query('tag_name') | regex_replace('^v', '') }}"
  tags:
    - reactotron

- name: Download reactotron release
  get_url:
    url: "https://github.com/infinitered/reactotron/releases/latest/download/reactotron-app_{{ reactotron_version }}_amd64.deb"
    dest: "/tmp/reactotron.deb"
  tags:
    - reactotron

- name: Remove Any previous reactotron
  become: true
  apt:
    name: reactotron
    state: absent
  tags:
    - reactotron

- name: Install reactotron.deb package
  become: true
  apt:
    deb: /tmp/reactotron.deb
  tags:
    - reactotron
