- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:codePassion-dot/.dotFiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./pop-os
  tags:
    - dotfiles
